name: flutter_note_app
description: A simple note app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^3.1.1
  freezed_annotation: ^2.4.4
  go_router: ^14.6.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  rxdart: ^0.28.0
  shared_preferences: ^2.3.3
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
  - family: Lexend
    fonts:
      - asset: assets/fonts/lexend/Lexend-Black.ttf
      - asset: assets/fonts/lexend/Lexend-Bold.ttf
      - asset: assets/fonts/lexend/Lexend-ExtraBold.ttf
      - asset: assets/fonts/lexend/Lexend-ExtraLight.ttf
      - asset: assets/fonts/lexend/Lexend-Light.ttf
      - asset: assets/fonts/lexend/Lexend-Medium.ttf
      - asset: assets/fonts/lexend/Lexend-Regular.ttf
      - asset: assets/fonts/lexend/Lexend-SemiBold.ttf
      - asset: assets/fonts/lexend/Lexend-Thin.ttf
  - family: Source Sans Pro
    fonts:
      - asset: assets/fonts/source_sans_pro/SourceSansPro-Black.ttf
      - asset: assets/fonts/source_sans_pro/SourceSansPro-BlackItalic.ttf
      - asset: assets/fonts/source_sans_pro/SourceSansPro-Bold.ttf
      - asset: assets/fonts/source_sans_pro/SourceSansPro-BoldItalic.ttf
      - asset: assets/fonts/source_sans_pro/SourceSansPro-ExtraLight.ttf
      - asset: assets/fonts/source_sans_pro/SourceSansPro-ExtraLightItalic.ttf
      - asset: assets/fonts/source_sans_pro/SourceSansPro-Italic.ttf
      - asset: assets/fonts/source_sans_pro/SourceSansPro-Light.ttf
      - asset: assets/fonts/source_sans_pro/SourceSansPro-LightItalic.ttf
      - asset: assets/fonts/source_sans_pro/SourceSansPro-Regular.ttf
      - asset: assets/fonts/source_sans_pro/SourceSansPro-SemiBold.ttf
      - asset: assets/fonts/source_sans_pro/SourceSansPro-SemiBoldItalic.ttf

